# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20161012_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='basket',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, to='market.Basket'),
        ),
    ]
